In [1]:
using XLSX
using LibPQ
using DataFrames

# Define the PostgreSQL database connection parameters
file = open("login_for_sql.txt", "r")
username = chomp(readline(file))
password = chomp(readline(file))
close(file)

conn = LibPQ.Connection("dbname=Symmetria user=$username password=$password")

# Define the directory containing the Excel files
dir_path = "./"

# Loop through each Excel file in the directory
for year in 2021:2021
    if year > 2007
        filename = "Arsreikningar-lifeyrissjoda_$year.xlsx"
    else
        filename = "Arsreikningar-lifeyrissjoda_$year.xls"
    end
    filepath = joinpath(dir_path, filename)
    
    # Open the Excel file and read in the three specified sheets
    funddata_sam = DataFrame(XLSX.readtable(filepath, "funddata sam")...)
    funddata_ser = DataFrame(XLSX.readtable(filepath, "funddata ser")...)
    funddata_hluti_3 = DataFrame(XLSX.readtable(filepath, "funddata hluti 3")...)
    
    # Loop through each row in the value matrix and insert the data into the PostgreSQL database
    for row in 4:size(funddata_sam, 1)
        for col in 6:size(funddata_sam, 2)
            # Get the relevant data for the current row and column
            fund_id = funddata_sam[2, col]
            subfund_id = funddata_sam[row, 1]
            value = funddata_sam[row, col]
            date = funddata_sam[1, 2]
            attribute1 = funddata_sam[row, col-4]
            attribute2 = funddata_sam[row, col-3]
            attribute3 = funddata_sam[row, col-2]
            attribute4 = funddata_sam[row, col-1]
            
            # Insert the data into the PostgreSQL database
            sql = "INSERT INTO public.funddata (value, fund_id, subfund_id, attribute1, attribute2, attribute3, date, attribute4) VALUES ($value, $fund_id, $subfund_id, $attribute1, $attribute2, $attribute3, '$date', $attribute4);"
            execute(conn, sql)
        end
    end
    
    for row in 4:size(funddata_ser, 1)
        for col in 6:size(funddata_ser, 2)
            # Get the relevant data for the current row and column
            fund_id = funddata_ser[2, col]
            subfund_id = funddata_ser[row, 1]
            value = funddata_ser[row, col]
            date = funddata_ser[1, 2]
            attribute1 = funddata_ser[row, col-4]
            attribute2 = funddata_ser[row, col-3]
            attribute3 = funddata_ser[row, col-2]
            attribute4 = funddata_ser[row, col-1]
            
            # Insert the data into the PostgreSQL database
            sql = "INSERT INTO public.funddata (value, fund_id, subfund_id, attribute1, attribute2, attribute3, date, attribute4) VALUES ($value, $fund_id, $subfund_id, $attribute1, $attribute2, $attribute3, '$date', $attribute4);"
            execute(conn, sql)
        end
    end
    
    for row in 4:size(funddata_hluti_3, 1)
        for col in 6:size(funddata_hluti_3, 2)
            # Get the relevant data for the current row and column
            fund_id = funddata_hluti_3[2, col]
            subfund_id = funddata_hluti_3[row, 1]
            value = funddata_hluti_3[row, col]
            date = funddata_hluti_3[1, 2]
            attribute1 = funddata_hluti_3[row, col-4]
            attribute2 = funddata_hluti_3[row, col-3]
            attribute3 = funddata_hluti_3[row, col-2]
            attribute4 = funddata_hluti_3[row, col-1]
            
            # Insert the data into the PostgreSQL database
            sql = "INSERT INTO public.funddata (value, fund_id, subfund_id, attribute1, attribute2, attribute3, date, attribute4) VALUES ($value, $fund_id, $subfund_id, $attribute1, $attribute2, $attribute3, '$date', $attribute4);"
            execute(conn, sql)
        end
    end
end

# Close the database connection
close(conn)

LoadError: SystemError: opening file "login_for_sql.txt": No such file or directory